### ISSUE TITLE
Sound alert

### ISSUE THREAD

**Issue by icebob** [tatyshev/pomidorus#4]
Hi,

thank you for this great app. Could you add sound alerts when the timer expired? Sometimes I'm working with a fullscreen app and I can't see the notification window.

Keep up the good work!

**Comment by tatyshev** [comment]
Hi, I'll think about how this behavior can be improved.

But maybe it does not depend much on me, because for the notification I use the standard <a href="https://developer.mozilla.org/ru/docs/Web/API/notification">Notification API</a> and I assume that this behavior should be covered by it.

Thanks for the report.

**Comment by tatyshev** [comment]
@icebob 
Added in [1.0.1](https://github.com/tatyshev/pomidorus/releases/tag/1.0.1). You can enable it in the settings.

**Comment by icebob** [comment]
Awesome, thank you!
